# Generated by Django 3.2.13 on 2023-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdata',
            name='fk_DrugoiReg_oks',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.DrugoiReg_oks'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_DrugoiReg_zu',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.DrugoiReg_zu'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_Enk_oks',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Enk_oks'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_Kn_oks',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.BezKn_oks'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_OtrSquaria_oks',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.OtrSquaria_oks'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_OtrSquaria_zu',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.OtrSquaria_zu'),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='fk_Uslovnye_oks',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Uslovnye_oks'),
        ),
    ]
