# Generated by Django 3.2.13 on 2023-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230331_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdata',
            name='date_act_zu',
        ),
        migrations.RemoveField(
            model_name='regdata',
            name='number_act_zu',
        ),
        migrations.AddField(
            model_name='regdata',
            name='numberNp',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='номер акта НП (ЗУ)'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='numberOot',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='номер акта ООТ (ЗУ)'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='numberSx',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='номер акта СХ (ЗУ)'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='numberVf',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='номер акта ВФ (ЗУ)'),
        ),
    ]
