# Generated by Django 3.2.13 on 2023-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230405_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdata',
            name='date_Np',
            field=models.DateField(blank=True, null=True, verbose_name='дата НП'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='date_Oot',
            field=models.DateField(blank=True, null=True, verbose_name='дата ООТ'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='date_Sx',
            field=models.DateField(blank=True, null=True, verbose_name='дата СХ'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='date_Vf',
            field=models.DateField(blank=True, null=True, verbose_name='дата ВФ'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='date_act_zu',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта ЗУ'),
        ),
        migrations.AddField(
            model_name='regdata',
            name='number_act_zu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='№ акта ЗУ'),
        ),
    ]
